### ISSUE TITLE
Ver qué índice o qué proceso había que cambiar en la vFacturae para que no desordenase el xml

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/BNI#1]

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/29e0050663d3f495ff08574ed4b9d3d6.png)

En la caja vXML de vFacturaE, hay que revisar este puntero ULTIMO que no venía bien en el original.
Estoy casi seguro de que es el problema que genera el desorden del xml que generamos.

**Comment by guillermocid** [comment]
esto ya está corregido en el 12653 por ti no?

**Comment by gregorioruiz** [comment]
Si. Mi duda es si al llevarlo a los otros servidores se va a actualizar el vfacturae o no. O al menos, tener documentado qué hay que revisar cuando lo pongamos a funcionar.
