### ISSUE TITLE
INFORMES

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#10]
En el presupuesto, tenemos que repasar el informe, suma por partidas, pero no pone el total
![ScreenClip.png](https://zube.io/files/gregorioruiz/5fb140b9618ec9bb60e64a37a37f8b8f.png)

**Comment by gregorioruiz** [comment]
Guille, te voy pasando notas que tienen que ver con los informes para que lo hagas si está claro o le preguntes a Ana para irlo haciendo.
Si tienes dudas de cómo usar este sistema, me preguntas para que luego sepamos que está hecho y volverlo a repasar antes de darlo por cerrado.
