### ISSUE TITLE
Crear y asignar almacén en el alta de pedido.

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#11]
Al generar el pedido desde el presupuesto, aparece el formulario para dar de alta el pedido. Puede ser que si, al dar de alta un nuevo almacén, pueda ver los que tengo dados de alta para más o menos seguir un orden.
![ScreenClip.png](https://zube.io/files/gregorioruiz/cc308e35248be1097416fcbba07cbdcd.png)

**Comment by gregorioruiz** [comment]
En estos casos, hay que comentar que usen primero el localizador para ver cuales tienen y cómo les han nombrado.
Esto es algo general en todo el programa. Cuando se recurre a hacer el alta desde los menús de ayuda de un dato, lo conveniente es antes ir a localizar para comprobar si ya está, etc.

![ScreenClip.png](https://zube.io/files/gregorioruiz/04b94c6d9f49c443250699f4c481089d.png)

**Comment by anacid** [comment]
Que asigne el AO-nº de pedido directamente a ese pedido.

**Comment by gregorioruiz** [comment]
Lo hace cuando se pulsa en la pestaña Obra, no en todos los pedidos.

**Comment by anacid** [comment]
Probado y lo asigna perfectamente
