### ISSUE TITLE
ALTA DE UN ARTICULO CON DESCOMPUESTO

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#12]
Desde un pedido puedo dar de alta un artículo, pero si ese artículo tiene descompuesto,  no me permite dar de alta artículos que formen parte de ese descompuesto del artículo
![ScreenClip.png](https://zube.io/files/gregorioruiz/dbc4c4fc4dfdf1ca71849f606dbf30f2.png)

**Comment by gregorioruiz** [comment]
Ok. Me pongo a hacer el menú del dato.

**Comment by anacid** [comment]
Ok, he dado de alta un artículo como unidad, y a su vez, le he dado el descompuesto, lo hace correctamente.
Lo doy por cerrado
