### ISSUE TITLE
TIPO DE IVA EN LINEAS DE PEDIDO

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#13]
Al dar de alta una línea de pedido, por defecto pone en tipo de IVA "Exento", cuando en todo está definido el "General". Yo creo que en principio por defecto debiera de poner "General", y modificarlo para los casos especiales.
![ScreenClip.png](https://zube.io/files/gregorioruiz/4478c5a7335cb0c7179e031ba464bc3a.png)

**Comment by gregorioruiz** [comment]
El cliente de ese pedido es exento de iva.

![ScreenClip.png](https://zube.io/files/gregorioruiz/15068dd8e193b6530c62b7319a2a1163.png)

He probado en otro pedido y sí pone General cuando se mete el artículo

![ScreenClip.png](https://zube.io/files/gregorioruiz/5eec13f6da8a0c5d36e429a0b7dbe40f.png)

**Comment by anacid** [comment]
Ok, si había comprobado en la ficha del cliente los datos, pero no lo vi.
