### ISSUE TITLE
SERVIR UN PEDIDO

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#14]
Al servir el pedido, considerado ya un presupuesto aceptado, no nos conversa el almacén, y el buscador no funciona, debemos ir con la flecha.
![ScreenClip.png](https://zube.io/files/gregorioruiz/60a1d3ecbb5306649d17d53f6c5d66c3.png)

**Comment by gregorioruiz** [comment]
![ScreenClip.png](https://zube.io/files/gregorioruiz/4d7c0e26b92da44301b425481bc8e739.png)

**Comment by gregorioruiz** [comment]
Efectivamente no funcionan los botones de serie y almacén, pero no sé si es necesario. Lo podemos dejar aparcado y lo volvemos a pensar cuando estén acabadas más cosas.

**Comment by anacid** [comment]
Ok como lo veas
