### ISSUE TITLE
CERTIFICACIONES - Traspasar a las siguientes certif. las líneas metidas a mano

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#15]
No descuenta las unidades facturadas, desde certificaciones del general.

![ScreenClip.png](https://zube.io/files/gregorioruiz/acb5a514e03323b2149c25e459a5c104.png)

**Comment by anacid** [comment]
Detalle del pedido
![ScreenClip.png](https://zube.io/files/gregorioruiz/993322a3c048bccc8d2f2ba37b6dc432.png)

**Comment by gregorioruiz** [comment]
He calculado y puesto una nueva columna : Certificado
Primero que funcione y luego si eso, ya sacamos lo pendiente en vez de lo certificado

![ScreenClip.png](https://zube.io/files/gregorioruiz/d8d0e2fd92d9fac84a4c5805c75b7c18.png)

**Comment by anacid** [comment]
En certificado si aparecen bien las unidades facturadas. 
Después de hacer la primera certificación he añadido un artículo la pedido, ese artículo al hacer las siguientes certificaciones no aparece, por lo que no puedo facturarlo.

**Comment by gregorioruiz** [comment]
Ahora aparece lo nuevo añadido en pedido. Pero ojo a lo que pasa si dejo añadir líneas en la certif. que no están en el pedido. Posiblemente sea mejor evitar esta posibilidad.

![ScreenClip.png](https://zube.io/files/gregorioruiz/5f009bbcb202aafa80dd220059c3dca7.png)

**Comment by gregorioruiz** [comment]
Queda pendiente que cuando se borre la última certificación, se recalcule el dato Certificado. Pero no será muy normal, así que puede esperar.

**Comment by anacid** [comment]
Ok a añadir un artículo en el pedido después de una primera certificación, al hacer la segunda si que aparece el artículo nuevo.

**Comment by anacid** [comment]
Pero siempre da de alta como si fuera FacturaE, comprobado al hacer las facturas.
