### ISSUE TITLE
ELIMINAR UNA PRE-FACTURA

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#16]
Quiero eliminar una pre-factura, pero me da error, no puedo.

![ScreenClip.png](https://zube.io/files/gregorioruiz/298e7dbd951929566b2af0613316bed4.png)

**Comment by anacid** [comment]
Detalle de la pre-factura
![ScreenClip.png](https://zube.io/files/gregorioruiz/a9518a2b37df1300931bd96a6f716ffd.png)

**Comment by anacid** [comment]
En albaranes, me ha generado el albarán, entiendo que lo ha hecho, en el momento que yo he dado a siguiente certificación.
![ScreenClip.png](https://zube.io/files/gregorioruiz/c52cde31bbd2c04d72c48d4af9a0136f.png)

**Comment by anacid** [comment]
Este es el detalle del albarán, aparentemente esta todo en blanco.

![ScreenClip.png](https://zube.io/files/gregorioruiz/0cf65370b6e60be2d4ee02267aae0a16.png)

**Comment by anacid** [comment]
En la pestaña de "Pedidos", aparecen los artículos correspondientes de dicho pedido, pero también artículos que no corresponden a ese pedido.
![ScreenClip.png](https://zube.io/files/gregorioruiz/3a638f6b20cba055b49b712deea8f01c.png)

**Comment by gregorioruiz** [comment]
Si una prefactura o factura aparece con las líneas deshabilitadas, es porque es una certificación.
En ese caso no se puede dar de baja desde la lista de facturas, sino desde la propia certificación para no liarla.

Lo comprobamos juntos y pensamos qué pestañas tienen que salir y cuales no en el caso de las certificaciones y facturas.
Quizá también falte poner en estas facturas abajo lo de certificación anterior, diferencia, etc. o cambiar arriba el título del formulario, que ponga factura-certificación o algo así.

**Comment by anacid** [comment]
Efectivamente la prefactura de una certificación se elimina desde "certificaciones", bien. 
El resto lo podemos ver cuando tu quieras.

**Comment by anacid** [comment]
La pre-factura, me deja eliminarla desde "Certificaciones", pero si voy a facturas de venta, esa factura sigue existiendo, y ahí no me deja borrarla.
![ScreenClip.png](https://zube.io/files/gregorioruiz/ce3246c7e3c9f1b1842b56af3fd69876.png)

**Comment by anacid** [comment]
Al eliminar un pre-factura desde certificación, las unidades certificadas no se eliminan, en el detalle del pedido sigue apareciendo como certificada 1 ud.
![ScreenClip.png](https://zube.io/files/gregorioruiz/6d25a2cb8d24b5f4602850b01d2dc7cf.png)

**Comment by anacid** [comment]
He vuelto a hacer una primera certificación con un artículo distinto al anterior, y ahora ya aparece bien lo certificado. 
Quizás tengamos que repasar el proceso

**Comment by gregorioruiz** [comment]
por qué narices me crea la extensión de factura electrónica de la factura cuando hago una certificación?
Lo hace si facturo un albarán?

**Comment by gregorioruiz** [comment]
La extensión de factura electrónica la creó Guillermo (o yo en sueños, porque no me acuerdo) pero no sé muy bien por qué hace falta que se cree en todas las facturas, cuando se puede hacer por pestaña en la factura como en todo el programa.
He puesto en el previo a la baja que lo borre en caso de existir y punto. 
Comentarlo con Guille

**Comment by gregorioruiz** [comment]
Ver por qué da un error al borrar la segunda certificación, pero no cuando borro la primera.
