### ISSUE TITLE
ALTA DE CONTACTO - Trabajador

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#17]
Modificar "Es transportista", por "Es trabajador", si se puede claro
![ScreenClip.png](https://zube.io/files/gregorioruiz/96e25ecad8e69d0b97c16946707bb5c3.png)

**Comment by anacid** [comment]
Si el contacto ya está dado de alta como trabajador, ocultar la pestaña de "datos facturaE"
![ScreenClip.png](https://zube.io/files/gregorioruiz/0d3c39e873aafebf8c8a5929b3bc8e79.png)

**Comment by anacid** [comment]
En el trabajador, al dar de alta la nómina, es nombre de la paga, lo pone en el nombre del trabajador.
![ScreenClip.png](https://zube.io/files/gregorioruiz/d351b145f13583db274f5aa9b2cc32c5.png)

**Comment by anacid** [comment]
Al seleccionar la obra, para hacer el reparto de la nómina, no en lista no aparece el nombre de la obra, cuando si está puesto.

![ScreenClip.png](https://zube.io/files/gregorioruiz/e5401cf1c404ef4bc07fe5e149337ebe.png)

**Comment by gregorioruiz** [comment]
Hechos 1 y 2
El 3 lo pone así el programa y no me parece mal. Lo comentamos
el 4, repasar dando de alta un nuevo pedido que sea obra, a ver si ahora crea bien ese nombre que debe aparecer ahí.

**Comment by anacid** [comment]
Ok a los puntos 1 y 2

**Comment by anacid** [comment]
El punto 4, he dado de alta un  nuevo presupuesto, y lo he pasado a pedido con nombre de obra, pero sigue sin aparecer el nombre de la obra, en las nóminas. Como eres hombre de poca fe lo puedes comprobar.

**Comment by gregorioruiz** [comment]
Hecho lo de ocultar la pestaña FacturaE, salvo para los clientes.
