### ISSUE TITLE
Albarán de compra

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#18]
Al generar la factura de compra, desde un albarán, que conserve el almacén que está seleccionado en el albarán.
![ScreenClip.png](https://zube.io/files/gregorioruiz/720d56b7ddbf87cabbb4a0632f9f1bd3.png)

**Comment by anacid** [comment]
En una factura de compra, que es un "Gasto", a la hora de hacer el reparto no aparece el nombre de la obra,

![ScreenClip.png](https://zube.io/files/gregorioruiz/34c25f6f03ee691190c16bc544dae63d.png)

**Comment by gregorioruiz** [comment]
El punto 1 hecho
El 2, creo que pasa lo mismo que con las nóminas. No todas las obras están bien cargadas con el nombre que figura en el pedido. 
Repasar ahora con un pedido nuevo o con alguno anterior que deje modificar la obra
