### ISSUE TITLE
PEDIDO - OBRA, materiales y movimientos

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#19]
En obra, materiales, sólo deben de aparecer las entradas desde compras o los traspasos entre almacenes. No las unidades que se certifican.
![ScreenClip.png](https://zube.io/files/gregorioruiz/f1df5d42093bf0daca95bddbebaa33df.png)

**Comment by anacid** [comment]
[ ]En obra, movimientos: que no se vean los movimientos nulos puesto que son los movimientos de las certificaciones.

![ScreenClip.png](https://zube.io/files/gregorioruiz/6a217d54ffd5d8684b8cbe71ba8c7c7a.png)

**Comment by gregorioruiz** [comment]
Si las unidades de obra están marcadas como no inventariables, lo hace bien.
