### ISSUE TITLE
Traspaso entre almacenes

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#20]
Comprobar la búsqueda de traspaso entre almacenes, porque con fecha de hoy día 10-11-2015, he hecho un traspaso y no aparece, si que en la fecha del traspaso esta para el día 11-11-2015. Quizás sea eso, le fecha 
![ScreenClip.png](https://zube.io/files/gregorioruiz/a44682c72147c3b6c57d2e46b9291cf4.png)

**Comment by anacid** [comment]
Cuando realicemos un traspaso que la fecha de entrada en el almacén de destino sea la misma que la de salida del almacén de origen. Y que no deje modificar la fecha de entrada.

![ScreenClip.png](https://zube.io/files/gregorioruiz/f06c7e9e5b53962dbcc179e1f4823ca2.png)

**Comment by gregorioruiz** [comment]
Hecho. Comprobar.
