### ISSUE TITLE
CERTIFICACIONES, pre-facturas.

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#22]
[ ]Si damos de alta un artículo en una pre-factura, que no cambie el orden, que lo deje donde lo hemos dado de alta, o sea, si lo ponemos al final, que en la factura aparezca al final
![ScreenClip.png](https://zube.io/files/gregorioruiz/1b2f101284a18c08c172c2d433f5ab17.png)

**Comment by anacid** [comment]
Dudas que nos pueden surgir al hacer una segunda certificación:
1º.- Hacemos doble clic en la factura para hacer la siguiente certificación, una vez en la factura de venta: no vemos que sea la primera certificación, a la hora de facturar los artículos aparecen las unidades facturas, pero no el total del pedido, no se muy bien cuantas tengo que facturar. Si quieres lo podemos ver para comentarlo

![ScreenClip.png](https://zube.io/files/gregorioruiz/da3912bfc5720794594d6b9b2ee7c5f8.png)

**Comment by gregorioruiz** [comment]
Hecho lo de que se vea la cantidad que figura en pedido. Probar y comentamos.

**Comment by anacid** [comment]
Ya pasa las líneas añadidas en el pedido después de hacer certificaciones.
