### ISSUE TITLE
Reordenar las líneas de los informes.

### ISSUE THREAD

**Issue by guillermocid** [gregorioruiz/BNI#23]
Al crear un albaran desde todo el pedido, aparecen los titulos como seleccionables, pero no estan bien asignados a cada articulo

Al crear albarán desde la selección, no pasa los títulos.

**Comment by gregorioruiz** [comment]
Revisados los 4 botones de cómo servir un pedido.

**Comment by anacid** [comment]
En presupuestos, aparecen los títulos pero modifica el orden en el que se han dado de alta, a la hora de imprimir.
En pedidos, idem
En albaranes, aparecen los títulos y en el orden que se han dado de alta.
En facturas, no aparecen los títulos a la hora de imprimir.
