### ISSUE TITLE
Duplicacion de pedidos

### ISSUE THREAD

**Issue by guillermocid** [gregorioruiz/BNI#24]
Al duplicar un pedido, aparecen las lineas con los articulos, pero no se han sumado los valores al total del documento y me dice que no hay lineas por servir. Luego si han aparecido los valores

**Comment by guillermocid** [comment]
Los valores aparecen al cambiar el estado del pedido, aunque vuelvas a seleccionar el mismo estado de pendiente que tiene inicialmente

**Comment by gregorioruiz** [comment]
he probado a duplicar un pedido de sólo artículos y me funciona bien. 

No he probado aún a duplicar una obra.

**Comment by gregorioruiz** [comment]
Revisado
