### ISSUE TITLE
PEDIDO - OBRA - certificaciones - facturado

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#31]
Comprobar el total de facturado, no lleva bien el importe, no me ha suma la segunda certificación.
![ScreenClip.png](https://zube.io/files/gregorioruiz/27f448fc8cb3fed32c93d2cd688d16d7.png)

**Comment by gregorioruiz** [comment]
He probado y me lo hace bien. Se pueden mejorar los datos en las rejillas para que se entienda mejor.
