### ISSUE TITLE
No sé si ya está revisada la importación de clientes. En el 12000 hay algunos sin nombre y con datos mal llevados.

### ISSUE THREAD

**Issue by gregorioruiz** [gregorioruiz/BNI#33]

**Comment by guillermocid** [comment]
A falta de poder dar de alta algunos elementos como los paises o provincias, me parece que ya reliza bien la importación, de todas formas, hasta que no me envíen cada uno sus artículos, proveedores y clientes, creo que no lo podremos dar por finalziado...

**Comment by guillermocid** [comment]
Ya están realizadas todas las importaciones de los artículos y clientes que me han enviado.
