### ISSUE TITLE
Pedido de venta: Obra

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#40]
Seleccionada la pestaña de obra: podemos poner obra y descripción, es que cuando estamos trabajando en la obra no vemos por ningún sitio ni el nombre ni la descripción, ver si es posible que se pueda ver.
El número del pedido si aparece arriba en la pantalla.

![ScreenClip.png](https://zube.io/files/gregorioruiz/403428231a808240a17a273cf4600860.png)

**Comment by guillermocid** [comment]
Ya he introducido el titulo de la obra en un campo que no se puede modificar encima de los campos con los valores totales de la obra
