### ISSUE TITLE
Almacenes - Traspaso

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#7]
Al seleccionar el almacén y los artículos, no deben de aparecer los artículos que son unidades de obra.

**Comment by gregorioruiz** [comment]
Intentaré que funcione automático. En realidad no debería de verse sino que debe funcionar oculto para el cliente.

![ScreenClip.png](https://zube.io/files/gregorioruiz/68d199340ad5bc6fa3e831d1fbba1526.png)

**Comment by gregorioruiz** [comment]
Tengo que explicarte por qué desaparecen de la pantalla los traspasos. Es un asunto bastante extraño pero es como lo han programado los de Velneo.
Se resume en que si empezamos con un traspaso, mandamos al menos un artículo de uno a otro almacén y aceptamos, da por finalizado el traspaso y  ya no vuelve a aparecer. Sólo se ven los movimientos. 
No hay un documento de traspaso como tal.
Los que se ven en la rejilla cuando entramos son los vacíos.
