### ISSUE TITLE
Alta de un contacto

### ISSUE THREAD

**Issue by anacid** [gregorioruiz/BNI#8]
Tenemos que repasar el proceso de alta de un contacto, intento dar de alta un cliente, me lo marca como proveedor y me de error, si quieres te enseño un ejemplo

**Comment by gregorioruiz** [comment]
Ayer estuve probando con la versión nueva y no da ese problema, pero no logré ver la diferencia.
Prueba a ver si desde el formulario de alta de contacto, sin pasar por el botón de Más datos da también el error.  Si funciona, se lo quito y solucionado. De todas formas, comentar en el manual o al hacer la formación, que los den de alta cuando hacen la grabación de documentos.
